const BACKEND_URL = process.env.FASTAPI_URL || "http://localhost:8000";
const API_KEY = process.env.FASTAPI_API_KEY;

/**
 * Fields whose values are numeric identifiers that Excel will mangle into
 * scientific notation (e.g. 7.13E+08). Prefix them with a leading apostrophe
 * so Excel treats them as text on import.
 */
const NUMERIC_ID_FIELDS = new Set([
  "writer_ipi",
  "ipi",
  "iswc",
  "isrc",
  "cae",
  "duplicate", // value is the writer_ipi for dup rows
]);

type Row = {
  issue_id: string;
  work_id: string;
  field: string;
  original_value: string;
  suggested_value: string;
  decision?: string;
  notes?: string;
};

function csvEscape(v: unknown): string {
  const s = v == null ? "" : String(v);
  if (/[",\n]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

function safeValue(field: string, value: string): string {
  if (!value) return "";
  if (NUMERIC_ID_FIELDS.has(field)) return "'" + value;
  return value;
}

function buildCsv(opts: {
  catalogId: string;
  rows: Row[];
  publisher?: string;
}): string {
  const ts = new Date().toISOString().slice(0, 16).replace("T", " ");
  const header = [
    "issue_id",
    "work_id",
    "field",
    "original_value",
    "suggested_value",
    "decision",
    "notes",
  ].join(",");

  const lines = [
    `# Worksheet generated by Kataloghub — ${ts}`,
    `# Publisher: ${opts.publisher || "—"}`,
    `# Catalog: ${opts.catalogId}`,
    `# Numeric identifiers (writer_ipi, iswc, isrc) are quoted with a leading ' for Excel compatibility.`,
    header,
  ];

  for (const r of opts.rows) {
    lines.push(
      [
        r.issue_id,
        r.work_id,
        r.field,
        safeValue(r.field, r.original_value),
        safeValue(r.field, r.suggested_value),
        r.decision || "",
        r.notes || "",
      ]
        .map(csvEscape)
        .join(","),
    );
  }
  return lines.join("\n") + "\n";
}

export async function GET(
  _req: Request,
  ctx: { params: Promise<{ id: string }> },
) {
  const { id } = await ctx.params;
  const filename = `worksheet_${id}.csv`;

  // Try the FastAPI backend first
  try {
    const headers: Record<string, string> = {};
    if (API_KEY) headers["X-API-Key"] = API_KEY;
    const res = await fetch(
      `${BACKEND_URL}/api/catalogs/${encodeURIComponent(id)}/worksheet?format=json`,
      { headers, signal: AbortSignal.timeout(30_000) },
    );
    if (res.ok) {
      const json = (await res.json()) as Row[];
      const csv = buildCsv({ catalogId: id, rows: json });
      return new Response(csv, {
        headers: {
          "Content-Type": "text/csv; charset=utf-8",
          "Content-Disposition": `attachment; filename="${filename}"`,
        },
      });
    }
  } catch {
    // fall through
  }

  // Mock fallback — realistic mid-size publisher worksheet (15 issues across
  // a 30-work catalog, varied issue types).
  const rows: Row[] = [
    { issue_id: "I-001", work_id: "W-001", field: "writer_ipi",     original_value: "1234567",         suggested_value: "00712984310",     decision: "", notes: "" },
    { issue_id: "I-002", work_id: "W-002", field: "writer_ipi",     original_value: "",                suggested_value: "00345678901",     decision: "", notes: "" },
    { issue_id: "I-003", work_id: "W-003", field: "iswc",           original_value: "",                suggested_value: "T-100.003.003-3", decision: "", notes: "" },
    { issue_id: "I-004", work_id: "W-004", field: "role_code",      original_value: "WR",              suggested_value: "CA",              decision: "", notes: "" },
    { issue_id: "I-005", work_id: "W-005", field: "share",          original_value: "60",              suggested_value: "50",              decision: "", notes: "" },
    { issue_id: "I-006", work_id: "W-007", field: "writer_ipi",     original_value: "",                suggested_value: "00111222333",     decision: "", notes: "" },
    { issue_id: "I-007", work_id: "W-008", field: "iswc",           original_value: "T-100.008",       suggested_value: "T-100.008.008-8", decision: "", notes: "" },
    { issue_id: "I-008", work_id: "W-009", field: "isrc",           original_value: "SE-NRD-26-1",     suggested_value: "SE-NRD-26-10009", decision: "", notes: "" },
    { issue_id: "I-009", work_id: "W-010", field: "agreement_type", original_value: "XX",              suggested_value: "SE",              decision: "", notes: "" },
    { issue_id: "I-010", work_id: "W-011", field: "role_code",      original_value: "WR",              suggested_value: "CA",              decision: "", notes: "" },
    { issue_id: "I-011", work_id: "W-013", field: "duplicate",      original_value: "00712984310",     suggested_value: "00712984310",     decision: "", notes: "" },
    { issue_id: "I-012", work_id: "W-014", field: "writer_ipi",     original_value: "",                suggested_value: "00345678901",     decision: "", notes: "" },
    { issue_id: "I-013", work_id: "W-015", field: "iswc",           original_value: "T-100.015.015-X", suggested_value: "T-100.015.015-6", decision: "", notes: "" },
    { issue_id: "I-014", work_id: "W-001", field: "writer_name",    original_value: "Erik Anderson",   suggested_value: "Erik Andersson",  decision: "", notes: "" },
    { issue_id: "I-015", work_id: "W-006", field: "share",          original_value: "40",              suggested_value: "33.33",           decision: "", notes: "" },
  ];
  const csv = buildCsv({ catalogId: id, rows, publisher: "Example Publishing AB" });
  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
